### ISSUE TITLE
Incorrect Racial Abilities

### ISSUE THREAD

**Issue by Rootbiscuit** [LaughingHyena279/Not-Skyrim#1]
A newly created character receives vanilla racial abilities instead of the Imperious versions.

**Comment by LaughingHyena279** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Incorrect Racial Abilities](https://trello.com/c/A1lWQ2xK/1-incorrect-racial-abilities)

**Comment by LaughingHyena279** [comment]
Fixed in next update.
