### ISSUE TITLE
bfb ulfric and ganmar

### ISSUE THREAD

**Issue by KNGLogan** [LaughingHyena279/Not-Skyrim#2]
![ScreenShot1](https://user-images.githubusercontent.com/66355096/93659304-6129cb00-fa09-11ea-8d90-e961d6cd3f53.png)
![ScreenShot2](https://user-images.githubusercontent.com/66355096/93659306-65ee7f00-fa09-11ea-8a60-2406932fb7c3.png)

**Comment by KNGLogan** [comment]
oops wrong name

**Comment by LaughingHyena279** [comment]
Should be fixed with recent update.
