### ISSUE TITLE
Didnt even get to load

### ISSUE THREAD

**Issue by KaiRoman** [LaughingHyena279/Not-Skyrim#4]
i cant seem to fully load into the game, i get to the prison cell and before i can even see anything(i have a black screen) i turns to not responding in task manager and doesn't do anything

**Comment by LaughingHyena279** [comment]
Please attach the most recent crashlog from your /NetScriptFramework/Crash folder in 'Files Generated during playsessions launched with SKSE'
Also, have you added/changed any mods?

**Comment by LaughingHyena279** [comment]
Closed due to not able to replicate and no update.
